name: Publish JavaScript

on:
  workflow_dispatch:
    inputs:
      sha:
        description: Commit SHA
        type: string
      dry_run:
        description: Dry run
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_to_npm:
    name: to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.sha }}
      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - name: Set up wasm pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "v0.13.1"
      - name: Install dependencies
        run: npm install --no-package-lock
      - run: |
          printf '\n[profile.release]\nopt-level = "s"\n' >> Cargo.toml
          npm run build
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            npm publish --provenance --dry-run
          else
            npm publish --provenance
          fi
